dist: trusty

language: node_js
os: linux
node_js:
  - "12"

addons:
  chrome: stable

cache:
  directories:
    - ./node_modules

install:
  - npm install
script:
  - npm run build
  - npm run test --no-watch --no-progress --browsers=ChromeHeadlessNoSandbox
after_script:
  - cat ./coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js
deploy:
  strategy: git
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/cicd-demo
  keep_history: true
  on:
    branch: master
