language: node_js
node_js:
  - "12"
install:
  - npm install
script:
  - npm run build:pages
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/cicd-demo
  keep_history: true
  on:
    branch: master
